test module definition

diff --git a/.buildkite/heartbeat/heartbeat-pipeline.yml b/.buildkite/heartbeat/heartbeat-pipeline.yml
--- a/.buildkite/heartbeat/heartbeat-pipeline.yml
+++ b/.buildkite/heartbeat/heartbeat-pipeline.yml
@@ -30,81 +30,81 @@ steps:
     key: "heartbeat-mandatory-tests"
 
     steps:
-      - label: ":ubuntu: Heartbeat Unit Tests"
-        command: |
-          cd heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_UBUNTU_X86_64}"
-          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Ubuntu Unit Tests"
-
-      - label: ":rhel: Heartbeat Rhel9 Unit Tests"
-        command: |
-          cd heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_RHEL9}"
-          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Rhel9 Unit Tests"
-
-      - label: ":windows: Win-2016 Unit Tests"
-        key: "windows-2016"
-        command: |
-          Set-Location -Path heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_WIN_2016}"
-          machine_type: "${GCP_WIN_MACHINE_TYPE}"
-          disk_type: "pd-ssd"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Win-2016 Unit Tests"
-
-      - label: ":windows: Heartbeat Win-2022 Unit Test"
-        key: "windows-2022"
-        command: |
-          Set-Location -Path heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_WIN_2022}"
-          machine_type: "${GCP_WIN_MACHINE_TYPE}"
-          disk_type: "pd-ssd"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Win-2022 Unit Tests"
+#      - label: ":ubuntu: Heartbeat Unit Tests"
+#        command: |
+#          cd heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_UBUNTU_X86_64}"
+#          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Ubuntu Unit Tests"
+#
+#      - label: ":rhel: Heartbeat Rhel9 Unit Tests"
+#        command: |
+#          cd heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_RHEL9}"
+#          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Rhel9 Unit Tests"
+#
+#      - label: ":windows: Win-2016 Unit Tests"
+#        key: "windows-2016"
+#        command: |
+#          Set-Location -Path heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_WIN_2016}"
+#          machine_type: "${GCP_WIN_MACHINE_TYPE}"
+#          disk_type: "pd-ssd"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Win-2016 Unit Tests"
+#
+#      - label: ":windows: Heartbeat Win-2022 Unit Test"
+#        key: "windows-2022"
+#        command: |
+#          Set-Location -Path heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_WIN_2022}"
+#          machine_type: "${GCP_WIN_MACHINE_TYPE}"
+#          disk_type: "pd-ssd"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Win-2022 Unit Tests"
 
       - label: ":ubuntu: Heartbeat Go (Module) Integration Tests"
         command: |
@@ -115,6 +115,10 @@ steps:
           # defines the MODULE env var based on what's changed in a PR
           source .buildkite/scripts/changesets.sh
           defineModuleFromTheChangeSet heartbeat
+
+          source .buildkite/scripts/define_module.sh
+          defineModule heartbeat
+          # echo "~~~ New MODULE definition is $$NEW_MODULE"
 
           echo "~~~ Running tests"
           cd heartbeat
@@ -133,213 +137,211 @@ steps:
           - github_commit_status:
               context: "heartbeat: Go Integration Tests"
 
-      - label: ":ubuntu: Heartbeat Python (Module) Integration Tests"
-        command: |
-          set -euo pipefail
-          # defines the MODULE env var based on what's changed in a PR
-          source .buildkite/scripts/changesets.sh
-          defineModuleFromTheChangeSet heartbeat
+#      - label: ":ubuntu: Heartbeat Python (Module) Integration Tests"
+#        command: |
+#          set -euo pipefail
+#          # defines the MODULE env var based on what's changed in a PR
+#          source .buildkite/scripts/changesets.sh
+#          defineModuleFromTheChangeSet heartbeat
+#
+#          source .buildkite/scripts/define_module.sh
+#          defineModule heartbeat
+#          # echo "~~~ New MODULE definition is $$NEW_MODULE"
+#
+#          echo "~~~ Running tests"
+#          cd heartbeat
+#          mage pythonIntegTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_UBUNTU_X86_64}"
+#          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Python Integration Tests"
 
-          echo "~~~ Running tests"
-          cd heartbeat
-          mage pythonIntegTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_UBUNTU_X86_64}"
-          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Python Integration Tests"
-
-  - group: "Heartbeat Extended Tests"
-    key: "heartbeat-extended-tests"
-    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*(macOS|arm).*/
-
-    steps:
-      - label: ":linux: Heartbeat arm64 Unit Tests"
-        key: "arm-extended"
-        if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*arm.*/
-        command: |
-          cd heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "aws"
-          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
-          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
-        artifact_paths: "heartbeat/build/*.xml"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Linux arm64 Unit Tests"
-
-  - group: "Heartbeat Extended Testing MacOS"
-    key: "heartbeat-extended-tests-macos"
-    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
-
-    steps:
-      - label: ":mac: Heartbeat MacOS Unit Tests"
-      - label: ":mac: macOS x86_64 Unit Tests"
-        key: "macos-extended"
-        if:  build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
-        command: |
-          set -euo pipefail
-          source .buildkite/scripts/install_macos_tools.sh
-          cd heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "orka"
-          imagePrefix: "${IMAGE_MACOS_X86_64}"
-        artifact_paths:
-          - "metricbeat/build/*.xml"
-          - "metricbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: macOS x86_64 Unit Tests"
-
-      - label: ":mac: macOS arm64 Unit Tests"
-        key: "macos-arm-extended"
-        if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
-        command: |
-          set -euo pipefail
-          source .buildkite/scripts/install_macos_tools.sh
-          cd heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "orka"
-          imagePrefix: "${IMAGE_MACOS_ARM}"
-        artifact_paths:
-          - "metricbeat/build/*.xml"
-          - "metricbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: macOS arm64 Unit Tests"
-
-  - group: "Heartbeat Windows Extended Testing"
-    key: "heartbeat-extended-tests-win"
-    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*[Ww]indows.*/
-
-    steps:
-      - label: ":windows: Win-2019 Unit Tests"
-        key: "heartbeat-win-extended-2019"
-        command: |
-          Set-Location -Path heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_WIN_2019}"
-          machine_type: "${GCP_WIN_MACHINE_TYPE}"
-          disk_type: "pd-ssd"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Win-2019 Unit Tests"
-
-      - label: ":windows: Win-11 Unit Tests"
-        key: "heartbeat-windows-extended-11"
-        command: |
-          Set-Location -Path heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_WIN_11}"
-          machine_type: "${GCP_WIN_MACHINE_TYPE}"
-          disk_type: "pd-ssd"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Win-11 Unit Tests"
-
-      - label: ":windows: Win-10 Unit Tests"
-        key: "heartbeat-windows-extended-10"
-        command: |
-          Set-Location -Path heartbeat
-          mage build unitTest
-        retry:
-          automatic:
-            - limit: 3
-        agents:
-          provider: "gcp"
-          image: "${IMAGE_WIN_10}"
-          machine_type: "${GCP_WIN_MACHINE_TYPE}"
-          disk_type: "pd-ssd"
-        artifact_paths:
-          - "heartbeat/build/*.xml"
-          - "heartbeat/build/*.json"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Win-10 Unit Tests"
-
-  - wait: ~
-    # with PRs, we want to run packaging only if mandatory tests succeed
-    # for other cases, e.g. merge commits, we want to run packaging (and publish) independently of other tests
-    # this allows building DRA artifacts even if there is flakiness in mandatory tests
-    if: build.env("BUILDKITE_PULL_REQUEST") != "false"
-    depends_on: "heartbeat-mandatory-tests"
-
-  - group: "Heartbeat Packaging"
-    key: "heartbeat-packaging"
-    steps:
-      - label: ":ubuntu: Heartbeat Packaging Linux"
-        key: "heartbeat-package-linux"
-        env:
-          PLATFORMS: "+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
-          SNAPSHOT: true
-        command: |
-          cd heartbeat
-          mage package
-        retry:
-          automatic:
-            - limit: 3
-        timeout_in_minutes: 20
-        agents:
-          provider: gcp
-          image: "${IMAGE_UBUNTU_X86_64}"
-          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Packaging Linux"
-
-      - label: ":linux: Heartbeat Packaging Linux arm64"
-        key: "heartbeat-package-linux-arm"
-        env:
-          PLATFORMS: "linux/arm64"
-          PACKAGES: "docker"
-          SNAPSHOT: true
-        command: |
-          cd heartbeat
-          mage package
-        retry:
-          automatic:
-            - limit: 3
-        timeout_in_minutes: 20
-        agents:
-          provider: "aws"
-          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
-          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
-        notify:
-          - github_commit_status:
-              context: "heartbeat: Packaging Linux arm64"
+#  - group: "Heartbeat Extended Tests"
+#    key: "heartbeat-extended-tests"
+#    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*(macOS|arm).*/
+#
+#    steps:
+#      - label: ":linux: Heartbeat arm64 Unit Tests"
+#        key: "arm-extended"
+#        if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*arm.*/
+#        command: |
+#          cd heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "aws"
+#          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
+#          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
+#        artifact_paths: "heartbeat/build/*.xml"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Linux arm64 Unit Tests"
+#
+#      - label: ":mac: macOS x86_64 Unit Tests"
+#        key: "macos-extended"
+#        if:  build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
+#        command: |
+#          set -euo pipefail
+#          source .buildkite/scripts/install_macos_tools.sh
+#          cd heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "orka"
+#          imagePrefix: "${IMAGE_MACOS_X86_64}"
+#        artifact_paths:
+#          - "metricbeat/build/*.xml"
+#          - "metricbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: macOS x86_64 Unit Tests"
+#
+#      - label: ":mac: macOS arm64 Unit Tests"
+#        key: "macos-arm-extended"
+#        if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
+#        command: |
+#          set -euo pipefail
+#          source .buildkite/scripts/install_macos_tools.sh
+#          cd heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "orka"
+#          imagePrefix: "${IMAGE_MACOS_ARM}"
+#        artifact_paths:
+#          - "metricbeat/build/*.xml"
+#          - "metricbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: macOS arm64 Unit Tests"
+#
+#  - group: "Heartbeat Windows Extended Testing"
+#    key: "heartbeat-extended-tests-win"
+#    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*[Ww]indows.*/
+#
+#    steps:
+#      - label: ":windows: Win-2019 Unit Tests"
+#        key: "heartbeat-win-extended-2019"
+#        command: |
+#          Set-Location -Path heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_WIN_2019}"
+#          machine_type: "${GCP_WIN_MACHINE_TYPE}"
+#          disk_type: "pd-ssd"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Win-2019 Unit Tests"
+#
+#      - label: ":windows: Win-11 Unit Tests"
+#        key: "heartbeat-windows-extended-11"
+#        command: |
+#          Set-Location -Path heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_WIN_11}"
+#          machine_type: "${GCP_WIN_MACHINE_TYPE}"
+#          disk_type: "pd-ssd"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Win-11 Unit Tests"
+#
+#      - label: ":windows: Win-10 Unit Tests"
+#        key: "heartbeat-windows-extended-10"
+#        command: |
+#          Set-Location -Path heartbeat
+#          mage build unitTest
+#        retry:
+#          automatic:
+#            - limit: 3
+#        agents:
+#          provider: "gcp"
+#          image: "${IMAGE_WIN_10}"
+#          machine_type: "${GCP_WIN_MACHINE_TYPE}"
+#          disk_type: "pd-ssd"
+#        artifact_paths:
+#          - "heartbeat/build/*.xml"
+#          - "heartbeat/build/*.json"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Win-10 Unit Tests"
+#
+#  - wait: ~
+#    # with PRs, we want to run packaging only if mandatory tests succeed
+#    # for other cases, e.g. merge commits, we want to run packaging (and publish) independently of other tests
+#    # this allows building DRA artifacts even if there is flakiness in mandatory tests
+#    if: build.env("BUILDKITE_PULL_REQUEST") != "false"
+#    depends_on: "heartbeat-mandatory-tests"
+#
+#  - group: "Heartbeat Packaging"
+#    key: "heartbeat-packaging"
+#    steps:
+#      - label: ":ubuntu: Heartbeat Packaging Linux"
+#        key: "heartbeat-package-linux"
+#        env:
+#          PLATFORMS: "+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
+#          SNAPSHOT: true
+#        command: |
+#          cd heartbeat
+#          mage package
+#        retry:
+#          automatic:
+#            - limit: 3
+#        timeout_in_minutes: 20
+#        agents:
+#          provider: gcp
+#          image: "${IMAGE_UBUNTU_X86_64}"
+#          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Packaging Linux"
+#
+#      - label: ":linux: Heartbeat Packaging Linux arm64"
+#        key: "heartbeat-package-linux-arm"
+#        env:
+#          PLATFORMS: "linux/arm64"
+#          PACKAGES: "docker"
+#          SNAPSHOT: true
+#        command: |
+#          cd heartbeat
+#          mage package
+#        retry:
+#          automatic:
+#            - limit: 3
+#        timeout_in_minutes: 20
+#        agents:
+#          provider: "aws"
+#          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
+#          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
+#        notify:
+#          - github_commit_status:
+#              context: "heartbeat: Packaging Linux arm64"
