fix: change source for Noto-CJK font (#48418)
The source we were using to download the Noto CJK font stopped working.
Switch to the github's repository releases to find the required font.

(cherry picked from commit 9566a0ab928962e306a6cf558dceb13685a10fae)

# Conflicts:
#	dev-tools/packaging/templates/docker/Dockerfile.tmpl

diff --git a/dev-tools/packaging/templates/docker/Dockerfile.tmpl b/dev-tools/packaging/templates/docker/Dockerfile.tmpl
--- a/dev-tools/packaging/templates/docker/Dockerfile.tmpl
+++ b/dev-tools/packaging/templates/docker/Dockerfile.tmpl
@@ -171,6 +171,35 @@ RUN (npm i -g --loglevel verbose --production --engine-strict  @elastic/syntheti
 
 {{- if (and (eq .BeatName "heartbeat") (contains .from "ubuntu")) }}
 USER root
+<<<<<<< HEAD
+=======
+
+# Install the deps as needed by the exact version of playwright elastic synthetics uses
+# We don't use npx playwright install-deps because that could pull a newer version
+# Install additional fonts as well
+RUN for iter in {1..10}; do \
+    microdnf -y update && \
+    microdnf -y install fontconfig freetype cairo glib2 gtk3 pango xorg-x11-fonts-misc xorg-x11-fonts-Type1 \
+    at-spi2-atk atk at-spi2-core alsa-lib cups-libs dbus-libs libdrm mesa-libEGL mesa-libgbm nspr nss libX11 \
+    libX11-xcb libxcb libXcomposite libXdamage libXext libXfixes libXrandr libxkbcommon libxshmfence glib2 \
+    dbus-glib libicu mesa-libGL unzip \
+    findutils shadow-utils ca-certificates gawk libcap xz tar -y && \
+    mkdir -p /usr/share/fonts/google-noto && \
+    curl -L -o NotoSansCJKjp.zip https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/06_NotoSansCJKjp.zip && \
+    unzip NotoSansCJKjp.zip -d /usr/share/fonts/google-noto && \
+    rm -f NotoSansCJKjp.zip && \
+    microdnf -y remove unzip && \
+    curl -LO https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf && \
+    mv NotoSans-Regular.ttf /usr/share/fonts/google-noto && \
+    curl -LO https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf && \
+    mv NotoColorEmoji.ttf /usr/share/fonts/google-noto && \
+    fc-cache -fv && \
+    microdnf clean all && \
+    exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
+done; \
+(exit $exit_code)
+
+>>>>>>> 9566a0ab9 (fix: change source for Noto-CJK font (#48418))
 ENV NODE_PATH={{ $beatHome }}/.node
 RUN echo \
     $NODE_PATH \
