Fix jq installation

diff --git a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
--- a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
+++ b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
@@ -32,8 +32,15 @@ RUN for iter in {1..10}; do microdnf update -y && microdnf install -y shadow-uti
 {{- else }}
 # Installing jq needs to be installed after epel-release and cannot be in the same yum install command.
 RUN case "$arch" in aarch64) YUM_FLAGS="-x bind-license";; esac; \
-    for iter in {1..10}; do yum update --setopt=tsflags=nodocs -y $YUM_FLAGS && yum install --setopt=tsflags=nodocs -y epel-release &&  yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; done; (exit $exit_code) ; \
-    for iter in {1..10}; do yum update -y $YUM_FLAGS && yum install -y jq &&  yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
+    for iter in {1..10}; do \
+        yum update -y $YUM_FLAGS && \
+        yum install -y epel-release &&  \
+        yum update -y $YUM_FLAGS && \
+        yum install -y jq && \
+        yum clean all && \
+        exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; \
+    done; \
+    (exit $exit_code)
 {{- end }}
 
 LABEL \
