Added package group

diff --git a/.buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml b/.buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml
--- a/.buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml
+++ b/.buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml
@@ -45,25 +45,28 @@ steps:
   - wait: ~
     if: build.env("ManifestURL") == null
 
-  - label: "Package elastic-agent"
-    key: "package-full"
-    command: |
-      if [[ -z "${ManifestURL}" ]]; then
-        export ManifestURL=$(buildkite-agent meta-data get ManifestURL --default "")
-        if [[ -z "${ManifestURL}" ]]; then
-          echo ":broken_heart: Missing ManifestURL variable or empty string provided"
-          exit 1
-        fi
-      fi
-      if [[ -z "${MAGEFILE_VERBOSE}" ]]; then
-        export MAGEFILE_VERBOSE=$(buildkite-agent meta-data get MAGEFILE_VERBOSE --default "0")
-      fi
-      .buildkite/x-pack/elastic-agent/scripts/steps/package.sh
-    artifact_paths:
-      - "build/distributions/**/*"
-    agents:
-      provider: "gcp"
-      image: "family/platform-ingest-beats-ubuntu-2204"
-    retry:
-      manual:
-        allowed: true
+  - group: ":Packaging Artefacts"
+    key: "package"
+    steps:
+      - label: "Package elastic-agent"
+        key: "package-full"
+        command: |
+          if [[ -z "${ManifestURL}" ]]; then
+            export ManifestURL=$(buildkite-agent meta-data get ManifestURL --default "")
+            if [[ -z "${ManifestURL}" ]]; then
+              echo ":broken_heart: Missing ManifestURL variable or empty string provided"
+              exit 1
+            fi
+          fi
+          if [[ -z "${MAGEFILE_VERBOSE}" ]]; then
+            export MAGEFILE_VERBOSE=$(buildkite-agent meta-data get MAGEFILE_VERBOSE --default "0")
+          fi
+          .buildkite/x-pack/elastic-agent/scripts/steps/package.sh
+        artifact_paths:
+          - "build/distributions/**/*"
+        agents:
+          provider: "gcp"
+          image: "family/platform-ingest-beats-ubuntu-2204"
+        retry:
+          manual:
+            allowed: true
